#!/bin/bash

set -e

app=routing_eth
dir=

# Retrieve arguments
compile=$1
network=$2
dhcp_enable=$3

# Check network
if [ ${network: -2} != '.0' ]; then
    echo "Invalid network !"
    exit 1
fi
prefix_ip=${network::-2}

# Compile driver
if [ $(lsmod | grep ^asix | wc -l) == "0" ]; then
    echo "Install headers"
    sudo apt-get update
    sudo apt-get dist-upgrade -y
    sudo apt-get --assume-yes --force-yes install linux-headers-`uname -r`

    echo "Compile driver"
    make -C ../sources/drivers
    echo "Install driver"
    sudo make -C ../sources/drivers install
    sudo modprobe asix
    sudo echo "asix" >> /etc/modules
fi


# Set IP
ip=${prefix_ip}.1
echo "Set ip : ${ip}"
sudo ifconfig eth1 down
sudo ifconfig eth1 netmask 255.255.255.0 ${ip}
sudo ifconfig eth1 up

# DHCP server
if [ $dhcp_enable ]; then
    if [ ! -f /usr/sbin/dnsmasq ]; then
        echo "Install dnsmasq"
        sudo apt-get --assume-yes --force-yes install dnsmasq
    fi
    echo "Configure DHCP server"
    sudo cp ../conf/dhcpv4.tpl /etc/dnsmasq.d/${app}
    sudo sed "s|@PREFIX@|${prefix_ip}|g" -i /etc/dnsmasq.d/${app}
    sudo systemctl restart dnsmasq
fi

if [ ! -f /sbin/iptables ]; then
    sudo apt-get --assume-yes --force-yes install iptables
fi

sudo install -o root -g root -m 0755 ../conf/iptables.tpl /usr/local/bin/ynh-routing
sudo sed "s|@NETWORK@|${network}/24|g" -i /usr/local/bin/ynh-routing
sudo ynh-routing
