#!/bin/bash

set -e

app=routing_eth

# Remove driver
sudo rmmod asix
sudo sed -i "s/^asix$/# asix/g" /etc/modules

# DHCP
sudo rm /etc/dnsmasq.d/${app}

# Services
sudo systemctl stop ynh-routing
sudo systemctl disable ynh-routing
sudo rm /etc/systemd/system/ynh-routing.service
sudo rm /usr/local/bin/ynh-routing

exit 0
